### ISSUE TITLE
How to use the url parameter with an authenticated endpoint

### ISSUE THREAD

**Issue by SOG-web** [dillyboy/angular_material_data_grid#14]
Please how can I add something like jwt along the request to the url or oauth

**Comment by dillyboy** [comment]
Hi Raheem,

For this you don't have to do anything special. Just use an HTTP interceptor in your base application to attach the token. The grid will automatically pick it up while sending it's request to the backend.

**Comment by Pastorkid** [comment]
Thanks so much. I will try it out and give you feedback

**Comment by Pastorkid** [comment]
I am still @SOG-web but am responding with one of my co-worker account. We are both working on the project together
