### ISSUE TITLE
Programmatically set grid filters

### ISSUE THREAD

**Issue by raharrison** [dillyboy/angular_material_data_grid#21]
This might be user error and misunderstanding the config options, but I'm looking for a way to programmatically set the current list of grid filters applied. Essentially I have a set of preconfigured filters and when the user selects an option, it should apply that filter list to the current grid.

I saw that there was an `initialFilters` input option, but this doesn't impact the grid if modified after the initial load.

I've tried with a combination of the `entity` and `resetFilters` options but doesn't look like the grid sees the new filter list even if reloaded.

```html
  <amdg-grid
      [headings]="headings"
      [url]="url"
      [serverSidePagination]="true"
      [initialFilters]="gridFilters"
      [entity]="resetFilters"
      [resetFilters]="resetFilters">
  </amdg-grid>
```

and then the controller code that gets run whenever the user selects a preconfigured grid filter:

```typescript
this.gridFilters = [ ... ];
this.resetFilters = {};
```

**Comment by dillyboy** [comment]
Yes, the initialFilters array is only checked when it's first rendered. To achieve what you are looking for you can simply rerender the entire grid by enclosing it with a boolean using *ngIf. You can see an example of this
[here](https://github.com/dillyboy/angular_material_data_grid/blob/master/src/app/pages/demo/demo.component.html)

**Comment by raharrison** [comment]
> Yes, the initialFilters array is only checked when it's first rendered. To achieve what you are looking for you can simply rerender the entire grid by enclosing it with a boolean using *ngIf. You can see an example of this [here](https://github.com/dillyboy/angular_material_data_grid/blob/master/src/app/pages/demo/demo.component.html)

How would i go about prompting the re-render though from a function?

If for example i have a button or something which sets the initial filters to new values, it might also set a boolean for the ngIf, but something would also have to revert the value to true for the grid to render again.

Can only see that working if i set a timeout etc to set the flag back to true, but that seems far from ideal solution?

**Comment by dillyboy** [comment]
No need for a timeout, just look at the example.
