### ISSUE TITLE
Allow dynamic properties from responseEmit handler in clickable urlTemplate

### ISSUE THREAD

**Issue by raharrison** [dillyboy/angular_material_data_grid#22]
I am dynamically adding one of the columns' data to the `gridData` response using the `responseEmit` handler. This works perfectly for showing the data in the grid, but I am also wanting to use that same value in the clickable `urlTemplate` property of the same field.

It looks like the `urlTemplate` operates only on the raw data received from the endpoint and not from the `gridData` returned after the `responseEmit` hook is executed?

Below example constructs the heading, the data is not in the raw server response. The `urlTemplate` tries to use the same column value in it's path.

```typescript
headings = [{
  "fieldName": "something",
  "displayName": "Something",
  "type": "string",
  "clickable": "url",
  "other": {
    "urlTemplate": "/path/:something" // :something cannot be resolved here - returns just /path/
  }
}]
```

And then in the controller the dynamic column data is added to the `gridData`. This shows up ok in the grid itself, but doesn't allow the `clickable` url to function properly.

```typescript
onResponse(response: GridResponse): void {
   for(let i = 0; i < response.gridData.length; i++) {
      response.gridData[i].something = "computed value"
   }
}
```

Great component by the way!

**Comment by dillyboy** [comment]
If implemented correctly your top code section should work. Please check the demo code once again. To reach me faster just email me on **dilshan.liyanage@hotmail.co.uk**

**Comment by raharrison** [comment]
I put together a test repo: https://github.com/raharrison/angular-grid-test to show the issue with computed properties.

The router links work fine for existing properties on the response
![image](https://user-images.githubusercontent.com/2327200/228541722-ebbd1b66-cee5-484a-98b6-b96fc6cff1ac.png)

But not for computed properties in the `responseEmit` handler
![image](https://user-images.githubusercontent.com/2327200/228541942-f0978ad9-d90d-4280-ad8e-2023c11bc8c1.png)

(can run` server.js` to get the test data endpoint the grid uses)

**Comment by dillyboy** [comment]
Try something like this.

onResponse(response: GridResponse): void {
  for(let i = 0; i < response.gridData.length; i++) {
    response.gridData[i].computed = "computed";
    response.gridData[i].computedLink = `/other/${i}`;
  }
}

**Comment by raharrison** [comment]
Yep that works, thanks!
