### ISSUE TITLE
responseEmit doesnt get triggered.

### ISSUE THREAD

**Issue by muneebahmad0600** [dillyboy/angular_material_data_grid#5]
I am using my end point for URL. I can see the request being made to the backend which then receives the response, but the "responseEmit()" doesnt trigger at all. The response I am currently getting is not according to the requirement of the grid so I need to modify so the grid can be populated. Any help?

**Comment by dillyboy** [comment]
Make sure your grid response look like this for everything to work as usual. It's in the documentation.

{
  "payload": {
    "gridData": [...], 
    "totalCount": 1000, 
    "other": null 
  },
  "success": true, 
  "message": "SUCCESS" 
}
