### ISSUE TITLE
Server side on demand load from server no paging?

### ISSUE THREAD

**Issue by JasonSingleton** [dillyboy/angular_material_data_grid#6]
Is it possible to turn paging off and the grid requests data from the server on demand for the particular location in the data set?  

This of course would use virtual scrolling could be 10,000 rows for example (but it should only request the screen full from the server not all)

**Comment by dillyboy** [comment]
Hi Jason, I'm not sure if I understand your question correctly but if you are requesting so many rows without server side pagination it will take a lot of cpu power on the client side to render the pages specially when filters are applied and will mostly likely be laggy. I recommend to use server-side pagination if you have more than 1000 records.
